# Generated by Django 4.2.20 on 2025-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muxicon', '0002_alter_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
