# Generated by Django 4.2.20 on 2025-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muxicon', '0004_alter_song_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
